#!/usr/bin/bash

SESSION_NAME="vpn"
VPN_CONFIG="/home/quebn/.config/openvpn/config.ovpn"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "Session '$SESSION_NAME' already exists. Attaching..."
    tmux attach -t "$SESSION_NAME"
else
    echo "Creating new tmux session '$SESSION_NAME' and starting OpenVPN..."
    tmux new-session -d -s "$SESSION_NAME"
    tmux send-keys -t "$SESSION_NAME" "sudo openvpn --config \"$VPN_CONFIG\"" C-m
    tmux attach -t "$SESSION_NAME"
fi
