#!/bin/sh

dir=$HOME/.todo
name=todo

if [ ! -d "$dir" ]; then
    mkdir "$dir"
    touch "$dir/main.md"
fi

if [[ -z $TMUX ]] && [[ -z $(pgrep tmux) ]]; then
    tmux new-session -s $name -c $dir
    exit 0
fi

if ! tmux has-session -t=$name 2>/dev/null; then
    tmux new-session -ds $name -c $dir
fi

if [[ -z $TMUX ]]; then
    tmux a -d -t $name
else
    tmux switch-client -t $name
fi
